name: Build and Release APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessário para criar o Release automaticamente

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Build APK com Flet
        uses: flet-dev/flet-build-action@v1
        with:
          target: apk
          runner-python-version: "3.12"
          bundled-python-version: "3.12"
          build-number: ${{ github.run_number }}

      - name: Renomear APK para identificação
        run: |
          mkdir -p release
          mv build/apk/*.apk release/marju-express-v1.0.${{ github.run_number }}.apk

      - name: Criar Release e Enviar APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: "Marju Express - Versão 1.0.${{ github.run_number }}"
          body: "Atualização automática gerada via GitHub Actions na nuvem."
          files: release/*.apk
